### ISSUE TITLE
nginx virtual host

### ISSUE THREAD

**Issue by majestica** [antonlukin/3september#5]
Привет, был бы благодарен если бы вы могли прикрепить краткую инструкцию и виртуальный хост для  nginx. Спасибо

**Comment by antonlukin** [comment]
Добавил файл конфигурации nginx:
https://github.com/antonlukin/3september/blob/master/nginx.conf

Для установки нужно скачать зависимости командой `yarn` и запустить сервер, например, через pm2 командой `pm2 start server.js --name 3september` или `node server.js`
